title: Shyam Sundar
logo: /assets/img/photo.png
description: Aspiring Data Scientist with practical experience in SQL, Power BI, and Tableau,hands-on experience and proficient in Azure machine learning, Machine Learning as well as Deep Learning concepts such as Regression, Classification, Neural Networks, etc. Interested in delivering data-driven outcomes that fuel innovation and informed decision-making.
show_downloads: true
theme: jekyll-theme-Minimal 
